### ISSUE TITLE
add resque-multi-job-forks gem

### ISSUE THREAD

**Issue by ronaldmueller** [infopark/ses#6]
Currently resque starts a new ruby process for every job. This means every time a new document is indexed, a new ruby process is started.

Since starting a new ruby process takes around 100-200 milliseconds, this doesn't matter for normal work. But a 'rake index:all' processes all documents at once. So thousands of new ruby processes are started one after another, each just to send the index data for one document to Solr.

With the help of a gem like <code>resque-multi-job-forks</code> you can define, how many jobs will be executed before a new ruby process is started. To use the gem:
- the gem has to be added to the Gemfile
  
  <code>gem 'resque-multi-job-forks'</code>
- and the rake task 'index:worker:start' (in <code>vendor/gems/infopark_ses-6.9.0/lib/tasks/index.rake</code>) has to be extended by the param <code>JOBS_PER_FORK</code>: 

```
    desc "Start the worker" 
    task :start => :environment do 
      if worker_running? 
        puts "Worker is already running" 
      else 
        sh "nohup bundle exec rake environment resque:work QUEUE=#{Infopark::SES::Indexer.queue} JOBS_PER_FORK=5000 VERBOSE=1 PIDFILE=#{worker_pid_file} >> log/resque_worker_#{Infop 
ark::SES::Indexer.queue}.log 2>&1 &" 
      end 
    end 
```

This accelerates an 'index:all' nearly tenfold.

**Comment by BartekOchab** [comment]
After checking that ... it was also already integrated ...
