### ISSUE TITLE
Solr 5.x unterstützen

### ISSUE THREAD

**Issue by ronaldmueller** [infopark/ses#7]
Inzwischen gibt es Solr 5. Damit das infopark_ses Gem auch diese Version unterstützt, sollten einige Anpassungen vorgenommen werden. So kann man Solr 5 z.B. nicht über den "bundle exec ses-apache-solr" starten und stoppen. Es kommt zum

<pre>Error: Unable to access jarfile start.jar
Error: Unable to access jarfile start.jar
WARNING: Nothing to start, exiting ...</pre>

Alle Anpassungen sind unter https://cwiki.apache.org/confluence/display/solr/Major+Changes+from+Solr+4+to+Solr+5 beschrieben.

Gewünscht von der Uni HH

**Comment by BartekOchab** [comment]
Völlig Übersehen den Request.
Ist aber umgesetzt mit dem update auf Solr 6.0.
